### ISSUE TITLE
Config  Outdated

### ISSUE THREAD

**Issue by dsslimshaddy** [samueljseay/recaptcha#21] opened 2017-05-25 22:37 UTC
The config doc is outdated. 
`verify/2` works when giving option but does not take value from environmental variable.

**Comment by sobolevn** [comment] 2017-05-26 05:44
Thanks for the report!

Are you interested in making a PR?

**Comment by sobolevn** [comment] 2017-06-04 08:07
What I tried:

> » RECAPTCHA_PRIVATE_KEY=some MIX_ENV=dev iex -S mix
> Erlang/OTP 19 [erts-8.2.2] [source] [64-bit] [smp:4:4] [async-threads:10] [hipe] [kernel-poll:false] [dtrace]
> 
> Interactive Elixir (1.4.2) - press Ctrl+C to exit (type h() ENTER for help)
> iex(1)> System.get_env("RECAPTCHA_PRIVATE_KEY")
> "some"
> iex(2)> Recaptcha.Config.get_env(:recaptcha, :secret)
> "some"

**Comment by odiumediae** [comment] 2017-06-10 13:33
@sobolevn That was actually correct. Let me explain how to do it:

Put the following into your config, instead of what the `README.md` says:

```
config :recaptcha,
  public_key: System.get_env("RECAPTCHA_PUBLIC_KEY"),
  secret: System.get_env("RECAPTCHA_PRIVATE_KEY")
```

Export the env variables, e.g. in your `~/.bashrc` file:

```
export RECAPTCHA_PUBLIC_KEY="your public key"
export RECAPTCHA_PRIVATE_KEY="your private key"
```

Source the file in the command line, so the env vars are available:

```
source ~/.bashrc
```

Then restart the app and the vars should be available.

```


@samueljseay I'll submit a pull request to change the `README.md`.

**Comment by sobolevn** [comment] 2017-06-10 13:41
@odiumediae what we do here is actually a correct way to do it.
Here's how it works: https://github.com/samueljseay/recaptcha/blob/master/lib/recaptcha/config.ex#L16

There's a potential issue with `System.get_env`. Since it is executed only once in the compile time.
And our approach is the same way `phoenix` handles config.

**Comment by odiumediae** [comment] 2017-06-10 15:51
@sobolevn Then I've just learned something new, I was convinced this was an old way. But it actually solves a problem I was having in another app.

Thanks for clarifying!

**Comment by odiumediae** [comment] 2017-06-10 16:11
Actually, no, it doesn't work this way. At least not in with Elixir 1.4.4 and Phoenix 1.3-rc.2.

**Comment by sobolevn** [comment] 2017-06-10 16:20
@odiumediae does this test work? https://github.com/samueljseay/recaptcha/blob/master/test/recaptcha/config_test.exs#L10

**Comment by odiumediae** [comment] 2017-06-10 21:11
@sobolevn Yes, `mix test test/recaptcha/config_test.exs:10` runs successfully, but when I ran all tests, `test/recaptcha_test.exs:12` didn't, by the way.

**Comment by samueljseay** [comment] 2017-06-12 04:15
The library should support 3 different ways to declare config: https://github.com/samueljseay/recaptcha/releases/tag/2.1.1 

If that is not working for you @odiumediae we might need some more detail to try reproduce.

**Comment by samueljseay** [comment] 2017-06-19 22:07
Closing, but feel free to reopen if you run into more issues.

**Closed by samueljseay** 2017-06-19 22:07 UTC
