### ISSUE TITLE
cannot convert the given list to string

### ISSUE THREAD

**Issue by ghost** [samueljseay/recaptcha#57] opened 2020-01-13 07:15 UTC
I modified my `config.exs`, my template file, and controller as instructed in the README and got the following errors:

```** (exit) an exception was raised:
    ** (ArgumentError) cannot convert the given list to a string.

To be converted to a string, a list must either be empty or only
contain the following elements:

  * strings
  * integers representing Unicode code points
  * a list containing one of these three elements

Please check the given list or call inspect/1 to get the list representation, got:

[:missing_input_response, :invalid_input_secret]
```

Additionally, why does the library not use the Phoenix native format for HTML?
`<form name="someform" method="post" action="/somewhere">`  instead of `<%= form_for...`

**Comment by samueljseay** [comment] 2021-07-07 04:20
I can't reproduce this, closing for now.

**Closed by samueljseay** 2021-07-07 04:20 UTC
